import scrapy

class ProductItem(scrapy.Item):
    url = scrapy.Field()
    name = scrapy.Field()
    brand = scrapy.Field()
    model = scrapy.Field()
    sku = scrapy.Field()
    price = scrapy.Field()
    description = scrapy.Field()
    specifications = scrapy.Field()
    category = scrapy.Field()
    subcategory = scrapy.Field()
    images = scrapy.Field()
    manuals = scrapy.Field()
    documents = scrapy.Field()
    availability = scrapy.Field()
    rating = scrapy.Field()
    reviews_count = scrapy.Field()
    features = scrapy.Field()
    dimensions = scrapy.Field()
    weight = scrapy.Field()
    warranty = scrapy.Field()
    scraped_at = scrapy.Field()
    site = scrapy.Field()